# Generated by Django 3.1.4 on 2021-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210116_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_confirmed',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_secrete_code',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
