# Generated by Django 3.1.4 on 2021-01-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210116_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_secrete_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
