# Generated by Django 3.1.4 on 2021-01-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210117_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_secrete_code',
            new_name='email_secrete',
        ),
    ]
