# Generated by Django 3.1.4 on 2021-01-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210119_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_secrete',
            new_name='email_secret',
        ),
    ]
